name = "SimpleCache"
uuid = "535d1a1e-7fe7-4528-a7ba-13bd0fa9d36a"
authors = ["Volker Weißmann <volker.weissmann@gmx.de>"]
version = "0.1.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
